### ISSUE TITLE
Add a GUI to Scripture Phaser

### ISSUE THREAD

**Issue by NolantheNerd** [NolantheNerd/scripture_phaser#6]
## Description

Currently, the only way to interface with `scripture_phaser` is through the CLI tool (found in cli.py). Most users (and certainly almost all users on Windows) will want to use `scripture_phaser` through a GUI.

## Technical Requirements

- The GUI library/implementation needs to be platform independent, working on Windows, Linux and MacOS.
- Using the GUI should be default.
- All GUI functionality should interface directly with the API and bypass the CLI.
- The GUI should not call an external text editor to allow the user to input the passage text.

## Tasks

- [ ] Add a `useGUI` or similarly named option to the config file (default True)
- [ ] Choose a GUI library
- [ ] Implement Update Config Function (CLI "G")
- [ ] Implement Save Config Function (CLI "W")
- [ ] Implement List Function (CLI "L")
- [ ] Implement Toggle Mode Function (CLI "M")
- [ ] Implement Set Reference Function (CLI "R")
- [ ] Implement View Passage Function (CLI "V")
- [ ] Implement Set Translation Function (CLI "T")
- [ ] Implement View Translations Function (CLI "I")
- [ ] Implement Practice Passage Function (CLI "P")
- [ ] Implement Stats Viewer Function (CLI "S")
- [ ] Implement Reset Stats Function (CLI "Z")
- [ ] Include Version and License Info Somewhere

**Comment by NolantheNerd** [comment]
I've removed the ability to manually get/write the config from the CLI version of `scripture_phaser`, so I've also removed the necessity to include these features in the GUI. They were unnecessary features since the config is loaded and saved at the appropriate times by the backend anyway.
